ent_feedRateMmPerMin: 40
ent_millDiameterMm: 4
ent_millFlutesNumber: 4
ent_millRadialRunoutMm: 0.05
ent_spindleSpeedRpm: 600
r_backgroundColor: "0 0 0"
r_fps: 400
r_fullscreenMode: false
r_fullscreenResolutionHeight: 1080
r_fullscreenResolutionWidth: 1920
r_millPlateColor: "255 255 0"
r_steelColor: "192 192 192"
r_trajectoryColor: "255 0 0"
r_windowResolutionHeight: 600
r_windowResolutionWidth: 800
